FROM rust:1.82-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc-mingw-w64-x86-64 \
    git \
    ca-certificates \
    python3 \
    python3-pip \
    libssl-dev openssl osslsigncode \
    && rm -rf /var/lib/apt/lists/*

RUN rustup target add x86_64-pc-windows-gnu

RUN git clone --depth 1 https://github.com/Whispergate/Shellcrypt.git /opt/shellcrypt \
    && pip3 install --no-cache-dir --break-system-packages -r /opt/shellcrypt/requirements.txt

RUN chmod a+x /root \
    && mkdir -p /root/.cargo/registry \
    && chmod -R a+rwX /root/.cargo
ENV HOME=/root
ENV SHELLCRYPT=/opt/shellcrypt/main.py

WORKDIR /build
