FROM golang:1.23-bookworm

RUN go install mvdan.cc/garble@latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc-mingw-w64-x86-64 \
    git \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="/root/go/bin:${PATH}"

WORKDIR /build
