FROM debian:12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc-mingw-w64-x86-64 \
    g++-mingw-w64-x86-64 \
    clang \
    lld \
    llvm \
    nasm \
    make \
    cmake \
    git \
    curl \
    ca-certificates \
    python3 \
    python3-pip \
    python3-pefile \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build
