FROM debian:12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc-mingw-w64-x86-64 \
    curl \
    git \
    xz-utils \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sSf https://nim-lang.org/choosenim/init.sh | bash -s -- -y
ENV PATH="/root/.nimble/bin:${PATH}"

RUN nimble install winim -y

WORKDIR /build
